name: factchecker
channels:
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.14
  - aom=3.9.1
  - asttokens=3.0.0
  - attr=2.5.1
  - binutils_impl_linux-64=2.43
  - binutils_linux-64=2.43
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - cairo=1.18.4
  - comm=0.2.3
  - cuda-cccl_linux-64=12.9.27
  - cuda-command-line-tools=12.9.0
  - cuda-compiler=12.9.0
  - cuda-crt-dev_linux-64=12.9.41
  - cuda-crt-tools=12.9.41
  - cuda-cudart=12.9.37
  - cuda-cudart-dev=12.9.37
  - cuda-cudart-dev_linux-64=12.9.37
  - cuda-cudart-static=12.9.37
  - cuda-cudart-static_linux-64=12.9.37
  - cuda-cudart_linux-64=12.9.37
  - cuda-cuobjdump=12.9.26
  - cuda-cupti=12.9.19
  - cuda-cupti-dev=12.9.19
  - cuda-cuxxfilt=12.9.19
  - cuda-documentation=12.4.127
  - cuda-driver-dev=12.9.37
  - cuda-driver-dev_linux-64=12.9.37
  - cuda-gdb=12.9.19
  - cuda-libraries=12.9.0
  - cuda-libraries-dev=12.9.0
  - cuda-libraries-static=12.9.0
  - cuda-nsight=12.9.19
  - cuda-nvcc=12.9.41
  - cuda-nvcc-dev_linux-64=12.9.41
  - cuda-nvcc-impl=12.9.41
  - cuda-nvcc-tools=12.9.41
  - cuda-nvcc_linux-64=12.9.41
  - cuda-nvdisasm=12.9.19
  - cuda-nvml-dev=12.9.40
  - cuda-nvprof=12.9.19
  - cuda-nvprune=12.9.19
  - cuda-nvrtc=12.9.41
  - cuda-nvrtc-dev=12.9.41
  - cuda-nvrtc-static=12.9.41
  - cuda-nvtx=12.9.19
  - cuda-nvvm-dev_linux-64=12.9.41
  - cuda-nvvm-impl=12.9.41
  - cuda-nvvm-tools=12.9.41
  - cuda-nvvp=12.9.19
  - cuda-opencl=12.9.19
  - cuda-opencl-dev=12.9.19
  - cuda-profiler-api=12.9.19
  - cuda-sanitizer-api=12.9.27
  - cuda-toolkit=12.4.1
  - cuda-tools=12.9.0
  - cuda-version=12.9
  - cuda-visual-tools=12.9.0
  - cudnn=9.2.1.18
  - curl=8.13.0
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy=1.8.16
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gcc_impl_linux-64=13.3.0
  - gcc_linux-64=13.3.0
  - gdk-pixbuf=2.42.12
  - gds-tools=1.14.0.30
  - gettext=0.24.1
  - gettext-tools=0.24.1
  - gmp=6.3.0
  - graphite2=1.3.13
  - gxx_impl_linux-64=13.3.0
  - gxx_linux-64=13.3.0
  - harfbuzz=11.2.1
  - icu=75.1
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=8.18.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - krb5=1.21.3
  - lame=3.100
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - level-zero=1.22.1
  - libabseil=20250127.1
  - libasprintf=0.24.1
  - libasprintf-devel=0.24.1
  - libass=0.17.3
  - libcap=2.75
  - libcublas=12.9.0.13
  - libcublas-dev=12.9.0.13
  - libcublas-static=12.9.0.13
  - libcufft=11.4.0.6
  - libcufft-dev=11.4.0.6
  - libcufft-static=11.4.0.6
  - libcufile=1.14.0.30
  - libcufile-dev=1.14.0.30
  - libcufile-static=1.14.0.30
  - libcurand=10.3.10.19
  - libcurand-dev=10.3.10.19
  - libcurand-static=10.3.10.19
  - libcurl=8.13.0
  - libcusolver=11.7.4.40
  - libcusolver-dev=11.7.4.40
  - libcusolver-static=11.7.4.40
  - libcusparse=12.5.9.5
  - libcusparse-dev=12.5.9.5
  - libcusparse-static=12.5.9.5
  - libdeflate=1.24
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.6
  - libflac=1.4.3
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-devel_linux-64=13.3.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgettextpo=0.24.1
  - libgettextpo-devel=0.24.1
  - libgl=1.7.0
  - libglib=2.84.1
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgpg-error=1.55
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblzma=5.8.1
  - libnghttp2=1.64.0
  - libnpp=12.4.0.27
  - libnpp-dev=12.4.0.27
  - libnpp-static=12.4.0.27
  - libnsl=2.0.1
  - libnvfatbin=12.9.19
  - libnvfatbin-dev=12.9.19
  - libnvfatbin-static=12.9.19
  - libnvjitlink=12.9.41
  - libnvjitlink-dev=12.9.41
  - libnvjitlink-static=12.9.41
  - libnvjpeg=12.4.0.16
  - libnvjpeg-dev=12.4.0.16
  - libnvjpeg-static=12.4.0.16
  - libogg=1.3.5
  - libopengl=1.7.0
  - libopenvino=2025.0.0
  - libopenvino-auto-batch-plugin=2025.0.0
  - libopenvino-auto-plugin=2025.0.0
  - libopenvino-hetero-plugin=2025.0.0
  - libopenvino-intel-cpu-plugin=2025.0.0
  - libopenvino-intel-gpu-plugin=2025.0.0
  - libopenvino-intel-npu-plugin=2025.0.0
  - libopenvino-ir-frontend=2025.0.0
  - libopenvino-onnx-frontend=2025.0.0
  - libopenvino-paddle-frontend=2025.0.0
  - libopenvino-pytorch-frontend=2025.0.0
  - libopenvino-tensorflow-frontend=2025.0.0
  - libopenvino-tensorflow-lite-frontend=2025.0.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.47
  - libprotobuf=5.29.3
  - librsvg=2.58.4
  - libsanitizer=13.3.0
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libsqlite=3.49.2
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-devel_linux-64=13.3.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=257.4
  - libtiff=4.7.0
  - libudev1=257.4
  - libunwind=1.6.2
  - liburing=2.9
  - libusb=1.0.28
  - libuuid=2.38.1
  - libva=2.22.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.9.2
  - libxkbfile=1.1.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - matplotlib-inline=0.1.7
  - mpg123=1.32.9
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nsight-compute=2025.2.0.11
  - nspr=4.36
  - nss=3.111
  - ocl-icd=2.3.3
  - opencl-headers=2024.10.24
  - openh264=2.6.0
  - openssl=3.6.0
  - packaging=25.0
  - pango=1.56.3
  - parso=0.8.4
  - pcre2=10.45
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.1.1
  - pixman=0.46.0
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.15
  - pulseaudio-client=17.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.9.22
  - python-dateutil=2.9.0.post0
  - python_abi=3.9
  - pyzmq=27.0.2
  - readline=8.2
  - sdl2=2.32.54
  - sdl3=3.2.14
  - setuptools=80.1.0
  - six=1.17.0
  - snappy=1.2.1
  - stack_data=0.6.3
  - svt-av1=3.0.2
  - sysroot_linux-64=2.17
  - tbb=2022.1.0
  - tk=8.6.13
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.14.1
  - tzdata=2025b
  - wayland=1.23.1
  - wayland-protocols=1.43
  - wcwidth=0.2.13
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - xorg-libxtst=1.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zstd=1.5.7
  - pip:
      - annotated-types==0.7.0
      - anyio==4.9.0
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - click==8.1.8
      - decorator==4.4.2
      - diskcache==5.6.3
      - distro==1.9.0
      - fastapi==0.115.12
      - ffmpeg==1.4
      - ffmpeg-python==0.2.0
      - filelock==3.18.0
      - fsspec==2025.3.2
      - future==1.0.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - idna==3.10
      - imageio==2.31.1
      - imageio-ffmpeg==0.6.0
      - instaloader==4.11
      - jinja2==3.1.6
      - jiter==0.10.0
      - llama-cpp-python==0.3.9
      - llvmlite==0.43.0
      - markupsafe==3.0.2
      - more-itertools==10.7.0
      - moviepy==1.0.3
      - mpmath==1.3.0
      - networkx==3.2.1
      - numba==0.60.0
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.41
      - nvidia-nvtx-cu12==12.1.105
      - openai==1.79.0
      - openai-whisper==20240930
      - pillow==11.2.1
      - proglog==0.1.12
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - python-dotenv==1.1.0
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.31.0
      - sniffio==1.3.1
      - starlette==0.46.2
      - sympy==1.14.0
      - tiktoken==0.9.0
      - torch==2.4.1
      - tqdm==4.65.0
      - triton==3.0.0
      - typing-extensions==4.13.2
      - typing-inspection==0.4.0
      - urllib3==2.4.0
      - uvicorn==0.34.2
      - uvloop==0.21.0
      - watchfiles==1.0.5
      - websockets==15.0.1
      - yt-dlp==2025.10.14
prefix: /data/home/jak38842/opt/miniconda3/envs/factchecker
